

Vagrant.configure("2") do |config|

  config.vm.define "pc01" do |pc01|
      pc01.vm.box = "gusztavvargadr/windows-10"
      pc01.vm.provider "hyperv"
      pc01.vm.hostname = "win10-pc01-asterix"
      pc01.vm.communicator = "winrm"
      pc01.winrm.username = "administrator"
      pc01.winrm.password = "vagrant"
      pc01.vm.network "public_network"
      pc01.vm.provider "hyperv" do |h|
          h.memory = 2048
          h.cpus = 2
      end
  end

  config.vm.define "pc02" do |pc02|
    pc02.vm.box = "gusztavvargadr/windows-10"
    pc02.vm.provider "hyperv"
    pc02.vm.hostname = "win10-pc02-obelix"
    pc02.vm.communicator = "winrm"
    pc02.winrm.username = "administrator"
    pc02.winrm.password = "vagrant"
    pc02.vm.network "public_network"
    pc02.vm.provider "hyperv" do |h|
      h.memory = 2048
      h.cpus = 2
    end
  end
  
end